### PR TITLE
feat: Migrate to CDK v2

### PR DESCRIPTION
**Pull request by artyom-melnikov**
This is my attempt to migrate this library to CDK v2.
What I've achieved:
 - The typescript version of the library is built properly and can be used with CDK v2 (`^2.15.0`)

What are the issues:
 - I have no knowledge about `jsii` and the full compilation fails with `[ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created`
 - I didn't run any repository tests, I've tested it with a real amplify and CDK project

### CODE REVIEW

**Comment by drem-darios** [comment]
Any timeline as to when this PR will be merged and a release available?

**Comment by ammarkarachi** [comment]
@drem-darios @artyom-melnikov It looks like to L2 construct for AppSync is still in alpha which the CLI uses the particular library. Waiting on an update from CDK for it being officially supported

**Comment by dreamorosi** [comment]
Has anyone considered using the L1 constructs instead?

Given that v1 is in maintenance mode and it's not gonna receive any new feature / API / service doesn't it make more sense to unlock these use cases in Amplify CLI rather than hold off over an alpha module that doesn't have any ETA?

**Comment by sobolk** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-cli-export-construct/pull/46

**Comment by siegerts** [comment]
Hi @artyom-melnikov, apologies on the follow up here. We appreciate you taking the time to dig into the project and taking the time to open this PR. At this time, it was decided to open a new PR above for the updates. I apologize for the miscommunication here and appreciate the time and effort that you've spent on this.

**Pull request closed without merging**
